### ISSUE TITLE
plugin config link shows 404 after installation

### ISSUE THREAD

**Issue by lifeboy** [nutso/redmine-plugin-recurring-tasks#126] opened 2017-11-21 14:47 UTC
The https://mysite.com/settings/plugin/recurring_tasks link returns "404 not found".

Also, on the menu between Projects and Administration, the text displayed reads "
translation missing: en.label_recurring_tasks" and the link to https://mysite.com/recurring_tasks also gives a 404 error.

redmine-plugin-recurring-tasks 2.0.0-pre

Environment:
  Redmine version                3.2.6.stable
  Ruby version                   2.3.3-p222 (2016-11-21) [x86_64-linux]
  Rails version                  4.2.7.1
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.8.10
  Mercurial                      3.1.2
  Bazaar                         2.7.0
  Git                            2.1.4
  Filesystem                     
Redmine plugins:
  recurring_tasks                2.0.0-pre
  redmine_agile                  1.4.5
  redmine_checklists             3.1.10

**Comment by nutso** [comment] 2017-11-29 11:22
What errors show up in the server log? What is the folder name where the plugin is installed?

**Comment by lifeboy** [comment] 2017-11-29 11:34
I removed the plugin since this was a production server.  I'll re-install on a test server and will report it here.

**Comment by davidglassborow** [comment] 2018-01-10 15:00
I followed the installation instructions and came across the same issue.  It's a prod system so I had to roll back straight away.

  
    Redmine version                3.1.1.stable
    Ruby version                   2.0.0-p645 (2015-04-13) [i386-mingw32]
    Rails version                  4.2.4
    

Log file of error:

        Started GET "/redmine/recurring_tasks" for 127.0.0.1 at 2018-01-10 14:47:47 +0000

    ActionController::RoutingError (uninitialized constant RecurringTasksController):
      vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.4/lib/active_support/inflector/methods.rb:261:in `const_get'
      vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.4/lib/active_support/inflector/methods.rb:261:in `block in constantize'
      vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.4/lib/active_support/inflector/methods.rb:259:in `each'
      vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.4/lib/active_support/inflector/methods.rb:259:in `inject'
    <snip>

**Comment by nutso** [comment] 2018-05-13 23:50
Please ref the [README](https://github.com/nutso/redmine-plugin-recurring-tasks#installation) especially with regard to the directory name.  Instead of "redmine-plugin-recurring-tasks", please rename the folder to "recurring_tasks".

Duplicate of #104

**Closed by nutso** 2018-05-13 23:50 UTC
Labels: troubleshooting
